### ISSUE TITLE
not working with serialport Version: 1.3.0

### ISSUE THREAD

**Issue by bwired-nl** [rfxcom/node-rfxcom#26]
Hi
looks like it is not working with serialport version 1.3.0 which is already installed

Sent    : 0D,00,00,00,00,00,00,00,00,00,00,00,00,00

/home/pi/node_modules/serialport/serialport.js:450
        callback(err, result);
        ^
TypeError: undefined is not a function
    at /home/pi/node_modules/serialport/serialport.js:450:9
